name: Node test build

on: [push]

jobs:
  build-ts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: "yarn"

      - name: Instala dependencias
        run: yarn

      - name: Builda projeto
        run: yarn build

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: "yarn"
      - run: yarn
      - run: yarn lint
      - run: yarn build
